name: dbt build

# When this action will be executed
on:
  # Allow manual trigger 
  workflow_dispatch:
  # schedule:
  #   # Every 5 minutes
  #   - cron: "0/5 0 * * *"
  
jobs:
  dbt_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SUBMODULE_PERSONAL_ACCESS_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Install requirements.txt
        run: pip install -r requirements.txt
      - name: Install dbt dependencies
        run: dbt deps
      - name: dbt Build
        run: dbt build
