name: dbt build

on:
  workflow_dispatch:

env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
  dbt_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Install requirements.txt
        run: pip install -r requirements.txt
      - name: Install dbt dependencies
        run: dbt deps
      - name: dbt Build
        run: dbt build
